name: Publish

on:
  release:
    types: [published]

jobs:

  publish:
    uses: diamcircle/actions/.github/workflows/rust-publish.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
